### ISSUE TITLE
Falsly claims not installed

### ISSUE THREAD

**Issue by delprofundo** [gozup/serverless-ssm-fetch#1]
So this borks (sis 1.23.0) saying:

 Serverless plugin "serverless-ssm-fetch" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

Both are false. I've installed it manually and using SLS plugins and get the same result.

The only ambiguity with my setup is around the external parameter file. Can you please clarify what you mean when you say I can use an external param file with an example. IE: is serverlessFetch: in custom or in the external file under that circumstance? 

Oh what i mean is I have this

```
custom:
    local: ${FILE.....}
```

**Comment by gozup** [comment]
Hi @delprofundo,

There is an example of setup with a "nested" file in the repo.
https://github.com/gozup/serverless-ssm-fetch/tree/master/example

However, as it is explained in the README, the ssm parameters list "must" be set under "custom -> serverlessSsmFetch". Either if you set it inline or through a nested file.
But in your copy/paste you got a key "local" between "custom" and your nested file.
With this setup it won't work actually (should think about a custom path in next updates).

Regarding installation issue, the plugin is currently installed and works on my side on a large project that fetches more than 30 secret parameters. Deployments run like a charm.

About your problem, it seems to come from the installation more than from the plugin itself.
But Gonna dig into this today.

It the meantime try to fix your plugin conf setup to see if it solves the issue.

Cheers mate!
Emmanuel

**Comment by gozup** [comment]
Hey @delprofundo,

It actually was an issue on my side that is now fixed with the [latest release (1.0.1)](https://github.com/gozup/serverless-ssm-fetch/releases/tag/1.0.1).

npm install the new version of the plugin and it will work (should you follow the plugin configuration from the README.md file).

Have a good day!

**Comment by delprofundo** [comment]
thanks bud....I was stuck on fixing another issue so I'll have a go over this this evening, should sort me out in the meantime. I'll report back any issues.
