### ISSUE TITLE
It it possible to use the ssm parameters in the serverless config itself?

### ISSUE THREAD

**Issue by teodorescuserban** [gozup/serverless-ssm-fetch#10]
Example. 

I had initially:

```custom:
  stage: ${opt:stage, self:provider.stage}
  prefix: '/aws/ssm/parameter/blah'
  region: 'us-east-1'
  config:
    ...
    mem: ${ssm:${self:custom.prefix}/${self:provider.stage}/mem}
 ```

How should I call the parameters got with your plugin?

Thank you.

**Comment by gozup** [comment]
Hi @teodorescuserban ,

Not sure to understand your question since the syntax `${ssm:xxxx}` is serverless' native syntax.

Regards,
Emmanuel

**Comment by teodorescuserban** [comment]
I don't even remember what was that about. I guess I found a way around it or a proper way to do it.
Thank you for having a look though.
Cheers.
